import type { Metadata } from "next"
import localFont from "next/font/local"

import ClientOnly from "@/components/ClientOnly"
import Navbar from "@/components/Navbar"
import CartSidebar from "@/components/cart/CartSidebar"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const metropolis = localFont({
  src: [
    {
      path: '../fonts/Metropolis/Metropolis-Thin.otf',
      weight: '100'
    },
    {
      path: '../fonts/Metropolis/Metropolis-ExtraLight.otf',
      weight: '200'
    },
    {
      path: '../fonts/Metropolis/Metropolis-Light.otf',
      weight: '300'
    },
    {
      path: '../fonts/Metropolis/Metropolis-Regular.otf',
      weight: '400'
    },
    {
      path: '../fonts/Metropolis/Metropolis-Medium.otf',
      weight: '500'
    },
    {
      path: '../fonts/Metropolis/Metropolis-SemiBold.otf',
      weight: '600'
    },
    {
      path: '../fonts/Metropolis/Metropolis-Bold.otf',
      weight: '700'
    },
    {
      path: '../fonts/Metropolis/Metropolis-ExtraBold.otf',
      weight: '800'
    },
    {
      path: '../fonts/Metropolis/Metropolis-Black.otf',
      weight: '900'
    },
  ],
  variable: '--font-metropolis'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${metropolis.variable} font-avenir`}>
      <body>
        <ClientOnly>
          <Navbar />
          <CartSidebar />
        </ClientOnly>
        <div className="mt-[129px]">
          {children}
        </div>
      </body>
    </html>
  )
}
